# PyTorch with Jupyter Notebook
- 구글 코랩을 쓰는게 나을지 이게 나을지
    - 코랩은 어지간한 패키지 내장된 듯. code에서는 venv 내에서 pip 써야 함
- md 부분은 md 확장이 먹는 것 같다 더 낫구만.
    - 이걸로 갑시다.
- 드디어 나도 주피터 노트북 사용자!

## 기초공사

In [1]:
# 기본 준비물들
import numpy as np
import torch

from varname import nameof

def print_info(tensor:torch.FloatTensor):
    try:
        name_of_var = nameof(tensor)
    except:
        name_of_var = 'tensor'
    print(f'Rank(dim) of {name_of_var} is {tensor.dim()}')
    print(f'Size of {name_of_var} is {tensor.shape}')

## 텐서 조작 기초

In [2]:
t1 = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t1)

[0. 1. 2. 3. 4. 5. 6.]


In [5]:
print(f'rank(ndim) of t1 is {t1.ndim}')
print(f'shape of t1 is {t1.shape}')

rank(ndim) of t1 is 1
shape of t1 is (7,)


shape에서 `(7,)`는 `(1,7)`과 같다

In [6]:
t2 = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t2)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [7]:
print(f'rank(ndim) of t2 is {t2.ndim}')
print(f'shape of t2 is {t2.shape}')

rank(ndim) of t2 is 2
shape of t2 is (4, 3)


PyTorch를 한번 써보자
- 일단은 `FloatTensor`를 주로 쓸 듯
- `dim()`과 `shape`가 있고, `shape`는 `size()`와 같다.

In [3]:
pt1 = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(pt1)
print_info(pt1)
print(type(pt1.shape))
print(pt1.shape == pt1.size())
print(pt1.shape is pt1.size()) # 다른 인스턴스이므로 False

tensor([0., 1., 2., 3., 4., 5., 6.])
Rank(dim) of tensor is 1
Size of tensor is torch.Size([7])
<class 'torch.Size'>
True
False


In [9]:
pt2 = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(pt2)
print_info(pt2)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
Rank(dim) of tensor is 2
Size of tensor is torch.Size([4, 3])


In [10]:
print(pt2[:, 1])
print(pt2[1, 1])
print(pt2[1:, :-1])

tensor([ 2.,  5.,  8., 11.])
tensor(5.)
tensor([[ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Broadcasting
- 행렬을 더하거나 뺄 때는 크기가 같아야 함.
- 곱셈을 할 때는 A의 마지막 차원과 B의 첫번째 차원의 크기가 같아야 함
    - 2차원의 경우, A의 열과 B의 행 크기가 같아야 함
- 브로드캐스팅은 자동으로 크기를 맞춰서 연산을 수행
- **자동으로 이루어지므로 사용에 주의해야 함.**

In [11]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [12]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)
print(m1 * m2)

tensor([[4., 5.]])
tensor([[3., 6.]])


In [13]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)
print(m1 * m2)

tensor([[4., 5.],
        [5., 6.]])
tensor([[3., 6.],
        [4., 8.]])


- 위의 경우 브로드캐스팅 과정에서 행렬이 채워짐
```
[1, 2]
==> [[1, 2],
     [1, 2]]
[3]
[4]
==> [[3, 3],
     [4, 4]]
```

### 행렬 곱셈의 차이
- 행렬 곱셈은 .matmul, 원소 별 곱셈은 .mul

In [14]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print_info(m1)
print_info(m2)
print(m1.matmul(m2)) # 2 x 1
print_info(m1.matmul(m2)) # 2 x 1

Rank(dim) of tensor is 2
Size of tensor is torch.Size([2, 2])
Rank(dim) of tensor is 2
Size of tensor is torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Rank(dim) of tensor is 2
Size of tensor is torch.Size([2, 1])


In [15]:
print(m1 * m2)
print(m1.mul(m2))

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### 총합, 평균, 최대값, 최대값 인덱스
- sum, mean, man, argmax
- 함수에서 dim 인자를 통해 행 혹은 열을 선택할 수 있음
    - 2차원의 경우, dim = 0이면 행을 합쳐버리는 것이고, dim = 1이면 열을 합쳐벼리는 것.

In [16]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean())

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


In [17]:
print(t.sum(dim = 0))
print(t.mean(dim = 0))

tensor([4., 6.])
tensor([2., 3.])


In [18]:
print(t.sum(dim = 1))
print(t.mean(dim = 1))

tensor([3., 7.])
tensor([1.5000, 3.5000])


In [19]:
print(t.max())
print(t.argmax())

tensor(4.)
tensor(3)


In [20]:
t = torch.FloatTensor([[1, 5], [2, 3]])

print(t)
print(t.max(dim = 0)[0])
print(t.argmax(dim = 0))

tensor([[1., 5.],
        [2., 3.]])
tensor([2., 5.])
tensor([1, 0])


In [21]:
print(t.max(dim = 1)[0])
print(t.argmax(dim = 1))

tensor([5., 3.])
tensor([1, 1])


## 텐서 조작 추가

### 뷰 (중요!?)
- 원소의 수를 유지하면서 텐서의 크기를 변경

In [22]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft)
print_info(ft)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
Rank(dim) of tensor is 3
Size of tensor is torch.Size([2, 2, 3])


In [24]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print_info(ft.view([-1, 3]))

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
Rank(dim) of tensor is 2
Size of tensor is torch.Size([4, 3])
