# PyTorch with Jupyter Notebook
- 구글 코랩을 쓰는게 나을지 이게 나을지
    - 코랩은 어지간한 패키지 내장된 듯. code에서는 venv 내에서 pip 써야 함
- md 부분은 md 확장이 먹는 것 같다 더 낫구만.
    - 이걸로 갑시다.
- 드디어 나도 주피터 노트북 사용자!

## 기초공사

In [61]:
# 기본 준비물들
import numpy as np
import torch

from varname import nameof

def print_info(tensor:torch.FloatTensor):
    try:
        name_of_var = nameof(tensor, frame = 2)
    except:
        name_of_var = 'tensor'
    print(f'Rank(dim) of {name_of_var} is {tensor.dim()}')
    print(f'Size of {name_of_var} is {tensor.shape}')

## 텐서 조작 기초

### Basics

In [62]:
t1 = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t1)

[0. 1. 2. 3. 4. 5. 6.]


In [63]:
print(f'rank(ndim) of t1 is {t1.ndim}')
print(f'shape of t1 is {t1.shape}')

rank(ndim) of t1 is 1
shape of t1 is (7,)


shape에서 `(7,)`는 `(1,7)`과 같다

In [64]:
t2 = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t2)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [65]:
print(f'rank(ndim) of t2 is {t2.ndim}')
print(f'shape of t2 is {t2.shape}')

rank(ndim) of t2 is 2
shape of t2 is (4, 3)


PyTorch를 한번 써보자
- 일단은 `FloatTensor`를 주로 쓸 듯
- `dim()`과 `shape`가 있고, `shape`는 `size()`와 같다.

In [66]:
pt1 = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(pt1)
print_info(pt1)
print(type(pt1.shape))
print(pt1.shape == pt1.size())
print(pt1.shape is pt1.size()) # 다른 인스턴스이므로 False

tensor([0., 1., 2., 3., 4., 5., 6.])
Rank(dim) of pt1 is 1
Size of pt1 is torch.Size([7])
<class 'torch.Size'>
True
False


In [67]:
pt2 = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(pt2)
print_info(pt2)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
Rank(dim) of pt2 is 2
Size of pt2 is torch.Size([4, 3])


In [68]:
print(pt2[:, 1])
print(pt2[1, 1])
print(pt2[1:, :-1])

tensor([ 2.,  5.,  8., 11.])
tensor(5.)
tensor([[ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Broadcasting
- 행렬을 더하거나 뺄 때는 크기가 같아야 함.
- 곱셈을 할 때는 A의 마지막 차원과 B의 첫번째 차원의 크기가 같아야 함
    - 2차원의 경우, A의 열과 B의 행 크기가 같아야 함
- 브로드캐스팅은 자동으로 크기를 맞춰서 연산을 수행
- **자동으로 이루어지므로 사용에 주의해야 함.**

In [69]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [70]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)
print(m1 * m2)

tensor([[4., 5.]])
tensor([[3., 6.]])


In [71]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)
print(m1 * m2)

tensor([[4., 5.],
        [5., 6.]])
tensor([[3., 6.],
        [4., 8.]])


- 위의 경우 브로드캐스팅 과정에서 행렬이 채워짐
```
[1, 2]
==> [[1, 2],
     [1, 2]]
[3]
[4]
==> [[3, 3],
     [4, 4]]
```

### 행렬 곱셈의 차이
- 행렬 곱셈은 .matmul, 원소 별 곱셈은 .mul

In [72]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print_info(m1)
print_info(m2)
print(m1.matmul(m2)) # 2 x 1
print_info(m1.matmul(m2)) # 2 x 1

Rank(dim) of m1 is 2
Size of m1 is torch.Size([2, 2])
Rank(dim) of m2 is 2
Size of m2 is torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Rank(dim) of tensor is 2
Size of tensor is torch.Size([2, 1])


In [73]:
print(m1 * m2)
print(m1.mul(m2))

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### 총합, 평균, 최대값, 최대값 인덱스
- sum, mean, man, argmax
- 함수에서 dim 인자를 통해 행 혹은 열을 선택할 수 있음
    - 2차원의 경우, dim = 0이면 행을 합쳐버리는 것이고, dim = 1이면 열을 합쳐벼리는 것.

In [74]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean())

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


In [75]:
print(t.sum(dim = 0))
print(t.mean(dim = 0))

tensor([4., 6.])
tensor([2., 3.])


In [76]:
print(t.sum(dim = 1))
print(t.mean(dim = 1))

tensor([3., 7.])
tensor([1.5000, 3.5000])


In [77]:
print(t.max())
print(t.argmax())

tensor(4.)
tensor(3)


In [78]:
t = torch.FloatTensor([[1, 5], [2, 3]])

print(t)
print(t.max(dim = 0)[0])
print(t.argmax(dim = 0))

tensor([[1., 5.],
        [2., 3.]])
tensor([2., 5.])
tensor([1, 0])


In [79]:
print(t.max(dim = 1)[0])
print(t.argmax(dim = 1))

tensor([5., 3.])
tensor([1, 1])


## 텐서 조작 추가


### 뷰 (중요!?)
- 원소의 수를 유지하면서 텐서의 크기를 변경

In [80]:
ft = torch.FloatTensor([1, 2, 3, 4])
ftv1 = ft.view([-1,1])
print(ftv1)
print_info(ftv1)
ftv4 = ft.view([-1, 1, 1, 1])
print(ftv4)
print_info(ftv4)


tensor([[1.],
        [2.],
        [3.],
        [4.]])
Rank(dim) of ftv1 is 2
Size of ftv1 is torch.Size([4, 1])
tensor([[[[1.]]],


        [[[2.]]],


        [[[3.]]],


        [[[4.]]]])
Rank(dim) of ftv4 is 4
Size of ftv4 is torch.Size([4, 1, 1, 1])


In [81]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft)
print_info(ft)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
Rank(dim) of ft is 3
Size of ft is torch.Size([2, 2, 3])


In [82]:
ftv2 = ft.view([-1, 3]) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ftv2)
print_info(ftv2)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
Rank(dim) of ftv2 is 2
Size of ftv2 is torch.Size([4, 3])


In [83]:
ftv3 = ft.view([-1, 1, 3])
print(ftv3)
print_info(ftv3)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
Rank(dim) of ftv3 is 3
Size of ftv3 is torch.Size([4, 1, 3])


In [85]:
ft = torch.FloatTensor([[[0], [1], [2]]])
print(ft)
print_info(ft)

tensor([[[0.],
         [1.],
         [2.]]])
Rank(dim) of ft is 3
Size of ft is torch.Size([1, 3, 1])


In [86]:
fts = ft.squeeze()
print(fts)
print_info(fts)

tensor([0., 1., 2.])
Rank(dim) of fts is 1
Size of fts is torch.Size([3])


In [91]:
ftus = fts.unsqueeze(1)
print(ftus)
print_info(ftus)

tensor([[0.],
        [1.],
        [2.]])
Rank(dim) of ftus is 2
Size of ftus is torch.Size([3, 1])


In [93]:
ftvus = fts.view(-1, 1)
print(ftvus)
print_info(ftvus)

tensor([[0.],
        [1.],
        [2.]])
Rank(dim) of ftvus is 2
Size of ftvus is torch.Size([3, 1])


In [104]:
print(ftv3)
print_info(ftv3)
ftv3us = ftv3.unsqueeze(0).unsqueeze(-1)
print(ftv3us)
print_info(ftv3us)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
Rank(dim) of ftv3 is 3
Size of ftv3 is torch.Size([4, 1, 3])
tensor([[[[[ 0.],
           [ 1.],
           [ 2.]]],


         [[[ 3.],
           [ 4.],
           [ 5.]]],


         [[[ 6.],
           [ 7.],
           [ 8.]]],


         [[[ 9.],
           [10.],
           [11.]]]]])
Rank(dim) of ftv3us is 5
Size of ftv3us is torch.Size([1, 4, 1, 3, 1])


### 연결, 스택
- 연결(cat)은 합쳐버리는 것, 스택은 차원을 늘리는 것.

In [106]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [114]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
z = torch.FloatTensor([[9, 10], [11, 12]])
stacked = torch.stack((x, y, z))
print(stacked)
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])


In [119]:
print(torch.ones_like(stacked))
print(torch.zeros_like(stacked))

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


### 덮어쓰기 연산
- 연산 함수 뒤에 언더바를 붙이면 기존의 값을 덮어쓰기 한다.
    - 즉, `x.mul_(2)` 는 `x = x.mul(2)`과 같다

# 선형 회귀 (Linear Regression)
- 데이터
    - 훈련 데이터와 테스트 데이터
- 가설 수립
    - 선형 회귀의 가설은 1차 방정식
- 손실 계산
    - 비용 함수 = 손실 함수 = 오차 함수 = 목적 함수
    - cost fn = loss fn = error fn = objective fn
    - y의 오차 제곱의 평균. MSE(Mead Squared Error)
        - 이건 분산 구하는것과 같구만
    - 즉, $$cost(W, b) = \frac{1}{n} \sum_{i=1}^{n} \left[y^{(i)} - H(x^{(i)})\right]^2$$
- 경사 하강법
    - 학습률(알파)가 너무 크면 조정 과정에서 발산해 버리고, 너무 작으면 학습이 더뎌진다.

In [120]:
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# 현재 실습하고 있는 파이썬 코드를 재실행해도 다음에도 같은 결과가 나오도록 랜덤 시드(random seed)를 줍니다.
torch.manual_seed(1)

In [126]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

print(x_train)
print_info(x_train)
print(y_train)
print_info(y_train)

print(torch.cat([x_train, y_train], dim = 1))

tensor([[1.],
        [2.],
        [3.]])
Rank(dim) of x_train is 2
Size of x_train is torch.Size([3, 1])
tensor([[2.],
        [4.],
        [6.]])
Rank(dim) of y_train is 2
Size of y_train is torch.Size([3, 1])
tensor([[1., 2.],
        [2., 4.],
        [3., 6.]])


In [128]:
W = torch.zeros(1, requires_grad=True)  # 가중치 초기값 0, requres_grad는 학습을 통해 계속 변경되는 값을 의미
print(W)
b = torch.zeros(1, requires_grad=True)

tensor([0.], requires_grad=True)


In [129]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [130]:
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [140]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

W = torch.zeros(1, requires_grad=True)  # 가중치 초기값 0, requres_grad는 학습을 통해 계속 변경되는 값을 의미
print(W)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr = 0.01)    # lr은 leraning rate

nb_epochs = 2300 # 경사 하강법 반복수
for epoch in range(nb_epochs + 1):
    hypothesis = x_train * W + b
    cost = torch.mean((hypothesis - y_train) ** 2)
    optimizer.zero_grad()   # gradient를 0으로 초기화
    cost.backward() # 비용 함수를 미분하여 gradient 계산
    optimizer.step()    # W와 b 업데이트

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

tensor([0.], requires_grad=True)
Epoch    0/2300 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/2300 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/2300 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/2300 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/2300 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/2300 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/2300 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/2300 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/2300 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/2300 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/2300 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/2300 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/2300 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/2300 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/2300 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/2300 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/2300 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/2300 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/2300 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/2300 

## 자동 미분(Autograd)

In [141]:
w = torch.tensor(2.0, requires_grad=True) # 값이 2인 임의의 스칼라값 선언
# requires_grad = True : 이 텐서의 기울기를 저장하겠다는 의미
# 위에서 optimizer.zero_grad를 해주지 않으면 w가 유지됨

y = w ** 2
z = 2 * y + 5

z.backward()
print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 8.0


## 다중 선형 회귀
- $$H(x) = w_{1}x_{1} + w_{2}x_{2} + w_{3}x_{3} + b$$

In [143]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

# 훈련 데이터
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# 가중치 w와 편향 b 초기화
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))

Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563634
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497607
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435026
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375730
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319511
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215696
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167818
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079378


In [148]:
x_train = torch.cat([x1_train, x2_train, x3_train], dim = 1)
print(x_train)
print(x_train.shape[1])

tensor([[ 73.,  80.,  75.],
        [ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.]])
3


In [154]:
W = torch.zeros((x_train.shape[1], 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.00001)

nb_epochs = 2000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(W) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
            epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
        ))

Epoch    0/2000 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch  100/2000 hypothesis: tensor([152.7691, 183.6985, 180.9591, 197.0627, 140.1336]) Cost: 1.563634
Epoch  200/2000 hypothesis: tensor([152.7273, 183.7273, 180.9465, 197.0517, 140.1731]) Cost: 1.497607
Epoch  300/2000 hypothesis: tensor([152.6866, 183.7554, 180.9343, 197.0409, 140.2116]) Cost: 1.435026
Epoch  400/2000 hypothesis: tensor([152.6470, 183.7827, 180.9224, 197.0304, 140.2491]) Cost: 1.375730
Epoch  500/2000 hypothesis: tensor([152.6085, 183.8093, 180.9108, 197.0201, 140.2856]) Cost: 1.319511
Epoch  600/2000 hypothesis: tensor([152.5711, 183.8352, 180.8996, 197.0101, 140.3211]) Cost: 1.266222
Epoch  700/2000 hypothesis: tensor([152.5346, 183.8604, 180.8887, 197.0003, 140.3558]) Cost: 1.215696
Epoch  800/2000 hypothesis: tensor([152.4992, 183.8849, 180.8781, 196.9908, 140.3895]) Cost: 1.167818
Epoch  900/2000 hypothesis: tensor([152.4647, 183.9087, 180.8677, 196.9814, 140.4223]) Cost: 1.122429
Epoch 

In [173]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1.
model = nn.Linear(3,1)

# print(list(model.parameters()))

optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 200
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 10 == 0:
    # 100번마다 로그 출력
        print(y_train - (prediction - cost))
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

tensor([[31826.3926],
        [31857.4961],
        [31854.1152],
        [31870.9355],
        [31812.2656]], grad_fn=<SubBackward0>)
Epoch    0/200 Cost: 31667.599609
tensor([[1.8899],
        [1.2077],
        [0.6037],
        [0.8369],
        [0.8668]], grad_fn=<SubBackward0>)
Epoch   10/200 Cost: 0.517863
tensor([[ 1.1227],
        [ 0.3456],
        [-0.2508],
        [-0.0676],
        [ 0.1406]], grad_fn=<SubBackward0>)
Epoch   20/200 Cost: 0.227732
tensor([[ 1.1202],
        [ 0.3442],
        [-0.2530],
        [-0.0698],
        [ 0.1397]], grad_fn=<SubBackward0>)
Epoch   30/200 Cost: 0.227505
tensor([[ 1.1192],
        [ 0.3445],
        [-0.2535],
        [-0.0701],
        [ 0.1401]], grad_fn=<SubBackward0>)
Epoch   40/200 Cost: 0.227287
tensor([[ 1.1182],
        [ 0.3448],
        [-0.2540],
        [-0.0704],
        [ 0.1405]], grad_fn=<SubBackward0>)
Epoch   50/200 Cost: 0.227072
tensor([[ 1.1172],
        [ 0.3451],
        [-0.2544],
        [-0.0707],
        [ 

In [170]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.2306]], grad_fn=<AddmmBackward0>)
